- hosts: nginx-machine
  roles:
  - nginx

- hosts: master-machine
  roles:
  - docker
  - master

- hosts: worker-machine-1
  roles:
  - docker
  - worker

- hosts: worker-machine-2
  roles:
  - docker
  - worker