---
# tasks file for nginx
- name: 'install nginx with apt'
  become: true
  apt:
    pkg:
    - nginx
    state: latest
    update_cache: true
- name: 'nginx is started'
  become: true
  service:
    name: nginx
    state: started
- name: 'configure nginx load balancer'
  become: true
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: 'reload nginx'