all: 
  hosts: 
    nginx-machine:
  children:
    managers:
      hosts:
        manager-machine:
    workers:
      hosts:
        worker-machine-1:
        worker-machine-2:
  vars:
    ansible_user: jenkins
    ansible_ssh_private_key_file: "~/.ssh/ansible_id_rsa"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
