- hosts: nginx-machine
  roles:
  - nginx

- hosts: master-machine
  roles:
  - docker
  - manager

- hosts: workers
  roles:
  - docker
  - worker

# - hosts: worker-machine-2
#   roles:
#   - docker
#   - worker