---
# tasks file for worker

- name: 'Join Swarm'
  become: true
  community.docker.docker_swarm:
    state: join
    advertise_addr: "{{ inventory_hostname }}"
    join_token: "{{ hostvars['manager-machine']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'manager-machine:2377' ]
    