---
# tasks file for master
- name: add jenkins user
  become: true
  user: 
    name: jenkins
    groups: docker
    shell: /bin/bash
    append: true
- name: 'Initialise Docker Swarm'
  become: true
  community.docker.docker_swarm:
    state: present
  register: swarm_info